// Generated by gencpp from file yolact_ros_msgs/Box.msg
// DO NOT EDIT!


#ifndef YOLACT_ROS_MSGS_MESSAGE_BOX_H
#define YOLACT_ROS_MSGS_MESSAGE_BOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolact_ros_msgs
{
template <class ContainerAllocator>
struct Box_
{
  typedef Box_<ContainerAllocator> Type;

  Box_()
    : x1(0)
    , y1(0)
    , x2(0)
    , y2(0)  {
    }
  Box_(const ContainerAllocator& _alloc)
    : x1(0)
    , y1(0)
    , x2(0)
    , y2(0)  {
  (void)_alloc;
    }



   typedef int32_t _x1_type;
  _x1_type x1;

   typedef int32_t _y1_type;
  _y1_type y1;

   typedef int32_t _x2_type;
  _x2_type x2;

   typedef int32_t _y2_type;
  _y2_type y2;





  typedef boost::shared_ptr< ::yolact_ros_msgs::Box_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolact_ros_msgs::Box_<ContainerAllocator> const> ConstPtr;

}; // struct Box_

typedef ::yolact_ros_msgs::Box_<std::allocator<void> > Box;

typedef boost::shared_ptr< ::yolact_ros_msgs::Box > BoxPtr;
typedef boost::shared_ptr< ::yolact_ros_msgs::Box const> BoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolact_ros_msgs::Box_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolact_ros_msgs::Box_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolact_ros_msgs::Box_<ContainerAllocator1> & lhs, const ::yolact_ros_msgs::Box_<ContainerAllocator2> & rhs)
{
  return lhs.x1 == rhs.x1 &&
    lhs.y1 == rhs.y1 &&
    lhs.x2 == rhs.x2 &&
    lhs.y2 == rhs.y2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolact_ros_msgs::Box_<ContainerAllocator1> & lhs, const ::yolact_ros_msgs::Box_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolact_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros_msgs::Box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros_msgs::Box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros_msgs::Box_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros_msgs::Box_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros_msgs::Box_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros_msgs::Box_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolact_ros_msgs::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01b404007f6687249fa0f27eea3c1daf";
  }

  static const char* value(const ::yolact_ros_msgs::Box_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01b404007f668724ULL;
  static const uint64_t static_value2 = 0x9fa0f27eea3c1dafULL;
};

template<class ContainerAllocator>
struct DataType< ::yolact_ros_msgs::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolact_ros_msgs/Box";
  }

  static const char* value(const ::yolact_ros_msgs::Box_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolact_ros_msgs::Box_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x1\n"
"int32 y1\n"
"int32 x2\n"
"int32 y2\n"
;
  }

  static const char* value(const ::yolact_ros_msgs::Box_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolact_ros_msgs::Box_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Box_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolact_ros_msgs::Box_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolact_ros_msgs::Box_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLACT_ROS_MSGS_MESSAGE_BOX_H
