// Generated by gencpp from file yolact_ros_msgs/Detection.msg
// DO NOT EDIT!


#ifndef YOLACT_ROS_MSGS_MESSAGE_DETECTION_H
#define YOLACT_ROS_MSGS_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <yolact_ros_msgs/Box.h>
#include <yolact_ros_msgs/Mask.h>

namespace yolact_ros_msgs
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : class_name()
    , score(0.0)
    , box()
    , mask()  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : class_name(_alloc)
    , score(0.0)
    , box(_alloc)
    , mask(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _class_name_type;
  _class_name_type class_name;

   typedef double _score_type;
  _score_type score;

   typedef  ::yolact_ros_msgs::Box_<ContainerAllocator>  _box_type;
  _box_type box;

   typedef  ::yolact_ros_msgs::Mask_<ContainerAllocator>  _mask_type;
  _mask_type mask;





  typedef boost::shared_ptr< ::yolact_ros_msgs::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolact_ros_msgs::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::yolact_ros_msgs::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::yolact_ros_msgs::Detection > DetectionPtr;
typedef boost::shared_ptr< ::yolact_ros_msgs::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolact_ros_msgs::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolact_ros_msgs::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolact_ros_msgs::Detection_<ContainerAllocator1> & lhs, const ::yolact_ros_msgs::Detection_<ContainerAllocator2> & rhs)
{
  return lhs.class_name == rhs.class_name &&
    lhs.score == rhs.score &&
    lhs.box == rhs.box &&
    lhs.mask == rhs.mask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolact_ros_msgs::Detection_<ContainerAllocator1> & lhs, const ::yolact_ros_msgs::Detection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolact_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros_msgs::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros_msgs::Detection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros_msgs::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros_msgs::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros_msgs::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros_msgs::Detection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolact_ros_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9e8252cb1b190158c1553f6547a1db7";
  }

  static const char* value(const ::yolact_ros_msgs::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9e8252cb1b19015ULL;
  static const uint64_t static_value2 = 0x8c1553f6547a1db7ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolact_ros_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolact_ros_msgs/Detection";
  }

  static const char* value(const ::yolact_ros_msgs::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolact_ros_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string class_name\n"
"float64 score\n"
"Box box\n"
"Mask mask\n"
"\n"
"================================================================================\n"
"MSG: yolact_ros_msgs/Box\n"
"int32 x1\n"
"int32 y1\n"
"int32 x2\n"
"int32 y2\n"
"\n"
"================================================================================\n"
"MSG: yolact_ros_msgs/Mask\n"
"int32 width\n"
"int32 height\n"
"uint8[] mask # Mask encoded as bitset\n"
;
  }

  static const char* value(const ::yolact_ros_msgs::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolact_ros_msgs::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.class_name);
      stream.next(m.score);
      stream.next(m.box);
      stream.next(m.mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolact_ros_msgs::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolact_ros_msgs::Detection_<ContainerAllocator>& v)
  {
    s << indent << "class_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.class_name);
    s << indent << "score: ";
    Printer<double>::stream(s, indent + "  ", v.score);
    s << indent << "box: ";
    s << std::endl;
    Printer< ::yolact_ros_msgs::Box_<ContainerAllocator> >::stream(s, indent + "  ", v.box);
    s << indent << "mask: ";
    s << std::endl;
    Printer< ::yolact_ros_msgs::Mask_<ContainerAllocator> >::stream(s, indent + "  ", v.mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLACT_ROS_MSGS_MESSAGE_DETECTION_H
