// Generated by gencpp from file yolact_ros_msgs/Detections.msg
// DO NOT EDIT!


#ifndef YOLACT_ROS_MSGS_MESSAGE_DETECTIONS_H
#define YOLACT_ROS_MSGS_MESSAGE_DETECTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <yolact_ros_msgs/Detection.h>

namespace yolact_ros_msgs
{
template <class ContainerAllocator>
struct Detections_
{
  typedef Detections_<ContainerAllocator> Type;

  Detections_()
    : header()
    , detections()  {
    }
  Detections_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::yolact_ros_msgs::Detection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::yolact_ros_msgs::Detection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::yolact_ros_msgs::Detections_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolact_ros_msgs::Detections_<ContainerAllocator> const> ConstPtr;

}; // struct Detections_

typedef ::yolact_ros_msgs::Detections_<std::allocator<void> > Detections;

typedef boost::shared_ptr< ::yolact_ros_msgs::Detections > DetectionsPtr;
typedef boost::shared_ptr< ::yolact_ros_msgs::Detections const> DetectionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolact_ros_msgs::Detections_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolact_ros_msgs::Detections_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolact_ros_msgs::Detections_<ContainerAllocator1> & lhs, const ::yolact_ros_msgs::Detections_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolact_ros_msgs::Detections_<ContainerAllocator1> & lhs, const ::yolact_ros_msgs::Detections_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolact_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros_msgs::Detections_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolact_ros_msgs::Detections_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros_msgs::Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolact_ros_msgs::Detections_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros_msgs::Detections_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolact_ros_msgs::Detections_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolact_ros_msgs::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43a2950037c7fe870ad7ff1691f82218";
  }

  static const char* value(const ::yolact_ros_msgs::Detections_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43a2950037c7fe87ULL;
  static const uint64_t static_value2 = 0x0ad7ff1691f82218ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolact_ros_msgs::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolact_ros_msgs/Detections";
  }

  static const char* value(const ::yolact_ros_msgs::Detections_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolact_ros_msgs::Detections_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Detection[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: yolact_ros_msgs/Detection\n"
"string class_name\n"
"float64 score\n"
"Box box\n"
"Mask mask\n"
"\n"
"================================================================================\n"
"MSG: yolact_ros_msgs/Box\n"
"int32 x1\n"
"int32 y1\n"
"int32 x2\n"
"int32 y2\n"
"\n"
"================================================================================\n"
"MSG: yolact_ros_msgs/Mask\n"
"int32 width\n"
"int32 height\n"
"uint8[] mask # Mask encoded as bitset\n"
;
  }

  static const char* value(const ::yolact_ros_msgs::Detections_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolact_ros_msgs::Detections_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detections_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolact_ros_msgs::Detections_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolact_ros_msgs::Detections_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::yolact_ros_msgs::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLACT_ROS_MSGS_MESSAGE_DETECTIONS_H
