# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yolact_ros_msgs/Detection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import yolact_ros_msgs.msg

class Detection(genpy.Message):
  _md5sum = "b9e8252cb1b190158c1553f6547a1db7"
  _type = "yolact_ros_msgs/Detection"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string class_name
float64 score
Box box
Mask mask

================================================================================
MSG: yolact_ros_msgs/Box
int32 x1
int32 y1
int32 x2
int32 y2

================================================================================
MSG: yolact_ros_msgs/Mask
int32 width
int32 height
uint8[] mask # Mask encoded as bitset
"""
  __slots__ = ['class_name','score','box','mask']
  _slot_types = ['string','float64','yolact_ros_msgs/Box','yolact_ros_msgs/Mask']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       class_name,score,box,mask

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Detection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.class_name is None:
        self.class_name = ''
      if self.score is None:
        self.score = 0.
      if self.box is None:
        self.box = yolact_ros_msgs.msg.Box()
      if self.mask is None:
        self.mask = yolact_ros_msgs.msg.Mask()
    else:
      self.class_name = ''
      self.score = 0.
      self.box = yolact_ros_msgs.msg.Box()
      self.mask = yolact_ros_msgs.msg.Mask()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.class_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d6i().pack(_x.score, _x.box.x1, _x.box.y1, _x.box.x2, _x.box.y2, _x.mask.width, _x.mask.height))
      _x = self.mask.mask
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = yolact_ros_msgs.msg.Box()
      if self.mask is None:
        self.mask = yolact_ros_msgs.msg.Mask()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_name = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.score, _x.box.x1, _x.box.y1, _x.box.x2, _x.box.y2, _x.mask.width, _x.mask.height,) = _get_struct_d6i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.mask.mask = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.class_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_d6i().pack(_x.score, _x.box.x1, _x.box.y1, _x.box.x2, _x.box.y2, _x.mask.width, _x.mask.height))
      _x = self.mask.mask
      length = len(_x)
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(struct.Struct('<I%sB'%length).pack(length, *_x))
      else:
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = yolact_ros_msgs.msg.Box()
      if self.mask is None:
        self.mask = yolact_ros_msgs.msg.Mask()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.class_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.class_name = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.score, _x.box.x1, _x.box.y1, _x.box.x2, _x.box.y2, _x.mask.width, _x.mask.height,) = _get_struct_d6i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      self.mask.mask = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_d6i = None
def _get_struct_d6i():
    global _struct_d6i
    if _struct_d6i is None:
        _struct_d6i = struct.Struct("<d6i")
    return _struct_d6i
